### PR TITLE
fix: make sure manifest writes don't overlap

### LINKED ISSUE #21: Mangled output
In multi compiler mode with a shared cache, I am getting the following mangled output.

```
{
  "common_en-US.js": "common_en-US-cbe78523083d0159240f.js",
  "common_en-US.js.map": "common_en-US-cbe78523083d0159240f.js.map"
}  "common_fr-CA.js": "common_fr-CA-2cf11bd51dc92d8b0ee2.js",
  "common_fr-CA.js.map": "common_fr-CA-2cf11bd51dc92d8b0ee2.js.map"
}
```

This is inconsistent, sometimes the file is correct, sometimes it is as above

### PR DESCRIPTION
**Pull request by mastilver**
closes #21

### CODE REVIEW

**Comment by zuzusik** [comment]
The main question here - does it really fix #21? I don't see an appropriate test case added here. If it is hard to reproduce maybe we should ask reporters of #21 to test this fix with their local setup?

If it doesn't fix #21 then I don't see why it should be merged. As a step for #33 as supposed here
 https://github.com/danethurber/webpack-manifest-plugin/issues/33#issuecomment-314063783 ?
Don't think we need this step - we better fix #33 with one monolithic PR

File: lib/plugin.js [hunk 1]
```diff
@@ -94,20 +94,16 @@ ManifestPlugin.prototype.apply = function(compiler) {
...
-
-    if (this.opts.writeToFileEmit) {
-      var outputFolder = compilation.options.output.path;
-      var outputFile = path.join(outputFolder, this.opts.fileName);
+    var outputFolder = compilation.options.output.path;
+    var outputFile = path.join(outputFolder, this.opts.fileName);
 
+    const shouldUseNodeFs = compiler.outputFileSystem.constructor.name !== 'MemoryFileSystem' ||
+                                      this.opts.writeToFileEmit;
+    if (shouldUseNodeFs) {
```
Comment (zuzusik) [inline lib/plugin.js]: As far as I see, the logic used here breaks what was achieved with https://github.com/danethurber/webpack-manifest-plugin/pull/28, as it assumes the file should be output to both memory and file system - now when `writeToFileEmit` is set ti true, it will be output only to file system, and not to memory.

Comment (mastilver) [inline lib/plugin.js]: 👍  will fix that

**Comment by mastilver** [comment]
@zuzusik Thank you for reviewing this PR :)

Did you see #49, I think you could be a good help for me

I think I know what's causing the issue, I will try to write a test that reproduce it

File: lib/plugin.js [hunk 2]
```diff
@@ -94,20 +94,16 @@ ManifestPlugin.prototype.apply = function(compiler) {
...
-    };
-
-    if (this.opts.writeToFileEmit) {
-      var outputFolder = compilation.options.output.path;
-      var outputFile = path.join(outputFolder, this.opts.fileName);
+    var outputFolder = compilation.options.output.path;
+    var outputFile = path.join(outputFolder, this.opts.fileName);
 
+    const shouldUseNodeFs = compiler.outputFileSystem.constructor.name !== 'MemoryFileSystem' ||
+                                      this.opts.writeToFileEmit;
```
Comment (zuzusik) [inline lib/plugin.js]: this indentation looks broken, I think we should stick to 2 spaces everywhere, also I think it is little bit more readable if we put `||` on the new line:
```js
const shouldUseNodeFs = compiler.outputFileSystem.constructor.name !== 'MemoryFileSystem'
  || this.opts.writeToFileEmit;
```

File: spec/plugin.integration.spec.js [hunk 3]
```diff
@@ -0,0 +1,53 @@
+var fs = require('fs');
+var path = require('path');
+
+var _ = require('lodash');
+var webpack = require('webpack');
+
+var ManifestPlugin = require('../index.js');
+
+function webpackConfig (webpackOpts, opts) {
```
Comment (zuzusik) [inline spec/plugin.integration.spec.js]: let's be consistent with style here - we should stick to `function<name>(...) {}` style as it is used all over the project

I mean - there shouldn't be a space before `(`

Also it should be fixed in other places in this PR

File: lib/plugin.js [hunk 4]
```diff
@@ -94,20 +94,16 @@ ManifestPlugin.prototype.apply = function(compiler) {
...
-      }
-    };
-
-    if (this.opts.writeToFileEmit) {
-      var outputFolder = compilation.options.output.path;
-      var outputFile = path.join(outputFolder, this.opts.fileName);
+    var outputFolder = compilation.options.output.path;
+    var outputFile = path.join(outputFolder, this.opts.fileName);
 
+    const shouldUseNodeFs = compiler.outputFileSystem.constructor.name !== 'MemoryFileSystem' ||
```
Comment (zuzusik) [inline lib/plugin.js]: I know that `const` is much more appropriate here, but this file uses `var` all over the place (and even 2 previous lines use `var`)

So I guess we should stick to `var` and if we want to go with `const` we should create separate PR in which we do refactor all `var` to `const`

File: spec/plugin.spec.js [hunk 5]
```diff
@@ -62,7 +62,7 @@ function webpackCompile(webpackOpts, opts, cb) {
   var fs = compiler.outputFileSystem = new MemoryFileSystem();
 
   compiler.run(function(err, stats){
-    var manifestFile = JSON.parse( fs.readFileSync(manifestPath).toString() );
+    var manifestFile = JSON.parse(fs.readFileSync(manifestPath).toString());
```
Comment (zuzusik) [inline spec/plugin.spec.js]: I'd remove this changes as they are completely unrelated to this PR

**Comment by zuzusik** [comment]
Also added few style related comments here

File: lib/plugin.js (hunk 4 above)
Comment (zuzusik) [inline lib/plugin.js]: Also, as far as I see we do rely on internal implementation of [`memory-fs`](https://github.com/webpack/memory-fs) here. Not sure if it is a good idea - the class name can be changed at any time without implicating the API, so it wouldn't be a reason for new major version release.

Comment (zuzusik) [inline lib/plugin.js]: And another question here - what if someone provides custom memory file system which is implemented in the other way?

File: lib/plugin.js [hunk 6]
```diff
@@ -94,20 +94,16 @@ ManifestPlugin.prototype.apply = function(compiler) {
...
+                                      this.opts.writeToFileEmit;
+    if (shouldUseNodeFs) {
       fse.outputFileSync(outputFile, json);
+    } else {
+      compiler.outputFileSystem.mkdirpSync(path.dirname(outputFile));
```
Comment (zuzusik) [inline lib/plugin.js]: I wonder why `mkdirpSync` and not `mkdirp`?
Webpack docs only mention `mkdirp` [here](https://webpack.js.org/api/node/#custom-file-systems) so it might blow up for some custom FS that provides only `mkdirp` but doesn't provide `mkdirpSync`

**Comment by zuzusik** [comment]
One serious concern here: https://github.com/danethurber/webpack-manifest-plugin/pull/56/files#r126405642

File: lib/plugin.js (hunk 4 above)
Comment (mastilver) [inline lib/plugin.js]: I agree it's ugly but that the only way I could find to check if it's really `MemoryFileSystem`, if you have a better solution feel free to share it ;)

I'm note the only one doing it: https://github.com/gajus/write-file-webpack-plugin/blob/51167a8cf33ee0885805abd1fb85c8306f0eda27/src/index.js#L19

File: lib/plugin.js (hunk 6 above)
Comment (mastilver) [inline lib/plugin.js]: Should be `mkdirp.sync`

File: lib/plugin.js (hunk 4 above)
Comment (zuzusik) [inline lib/plugin.js]: What do you think about this proposal:

```js
var outputFolder = compilation.options.output.path;
var outputFile = path.join(outputFolder, this.opts.fileName);

compiler.outputFileSystem.mkdirp(path.dirname(outputFile));
compiler.outputFileSystem.writeFileSync(outputFile, json);  

if ( this.opts.writeToFileEmit) {
  fse.outputFileSync(outputFile, json);
}
```

Comment (mastilver) [inline lib/plugin.js]: That would only work when using `memory-fs`, see: https://github.com/webpack/webpack/blob/master/lib/node/NodeOutputFileSystem.js#L17
It doesn't have `writeFileSync`

Comment (mastilver) [inline lib/plugin.js]: this should work thought: 

```
compiler.outputFileSystem.mkdirp(path.dirname(outputFile));
if (isMemoryFs) {
  compiler.outputFileSystem.writeFileSync(outputFile, json);  
}

if (!isMemoryFs || this.opts.writeToFileEmit) {
  fse.outputFileSync(outputFile, json);
}
```

Comment (zuzusik) [inline lib/plugin.js]: Your code looks good, should work as expected 👍 I only assume it should use `mkdirp.sync`

What I want to achieve here is that we can skip `compiler.outputFileSystem.constructor.name !== 'MemoryFileSystem'` check

Overall impression - it is weird that different FSs used in WebPack have different sets of methods.

Comment (mastilver) [inline lib/plugin.js]: > I only assume it should use mkdirp.sync

Damn, I updated it :)

**Comment by mastilver** [comment]
@zuzusik PR updated, do you mind having another look

**Comment by mastilver** [comment]
@zuzusik I'm not relying anymore or `memory-fs`logic

Let me know what you think!
