### PR TITLE
fix: Only include initial chunks

### LINKED ISSUE #46: Do not add code splitting bundles into manifest
I want to use `require.ensure` for separating some large modules as DLL.
But `webpack-manifest-plugin` add it into manifest 
so chunks are loading immediately

### PR DESCRIPTION
**Pull request by a-x-**
closes #46 _Do not add code splitting bundles into manifest_

### CODE REVIEW

**Comment by mastilver** [comment]
Do we need the `omitDlls` options?

Couldn't you use `chunk.initial` or `chunk.isInitial()`?

**Comment by a-x-** [comment]
What is chunk.initial or chunk.isInitial()?
I cannot find them in the source code or documentation

**Comment by mastilver** [comment]
is a boolean on chunk that tell if they are required on initial run

`.filter(chunk => chunk.isInitial ? chunk. isInitial() : chunk.initial`

**Comment by a-x-** [comment]
Thank you,

As I understand isInitial might be a replacement for the `chunk.entrypoints`.

But I'm not sure to make this new logic default for all users in the next minor version.

**Comment by mastilver** [comment]
I doubt it can be considered as a breaking change,
to me it's definitely a fix, so it should land on a patch (BTW, some tests would be great! ;) )

File: lib/plugin.js [hunk 1]
```diff
@@ -42,24 +42,26 @@ ManifestPlugin.prototype.apply = function(compiler) {
...
-    _.merge(manifest, compilation.chunks.reduce(function(memo, chunk) {
-      var chunkName = chunk.name ? chunk.name.replace(this.opts.stripSrc, '') : null;
-
-      // Map original chunk name to output files.
-      // For nameless chunks, just map the files directly.
-      return chunk.files.reduce(function(memo, file) {
-        // Don't add hot updates to manifest
-        if (file.indexOf('hot-update') >= 0) {
+    _.merge(manifest, compilation.chunks
+      .filter(chunk => chunk => chunk.isInitial ? chunk.isInitial() : chunk.initial)
```
Comment (mastilver) [inline lib/plugin.js]: extra `chunk => `

**Comment by a-x-** [comment]
done

**Comment by Ianfeather** [comment]
@mastilver Hi! First of all thanks for your work on this project, we use it in the asset-pipeline at BuzzFeed. 

Unfortunately this change broke one of our applications this morning as it was relying on the dynamic chunks being included in the asset-manifest. We use these manifest entries to preload bundles ahead of time with `link[rel=preload]`. We can probably find some alternative but it would be great if you would consider having this as an option. I think this is a very legitimate use case.

**Comment by a-x-** [comment]
Hey, we wanted to make it optional initially 😂

**Comment by mastilver** [comment]
@Ianfeather Damn, I was really hoping for my first release to go smoothly... :/

I will revert that change for now, we can think for another solution later

**Comment by a-x-** [comment]
@Ianfeather, you should use `chunk-manifest-webpack-plugin`

my position, this change should be default but major
@mastilver, what about you?

**Comment by mastilver** [comment]
@Ianfeather `webpack-manifest-plugin@1.0.2` released :)

**Comment by mastilver** [comment]
@a-x- I thing the right path to take is: by default include every single possible assets into the manifest and be able to have some filtering, I will put my thought down on an issue over the week-end, I will be happy to get your thoughts on that ;)

**Comment by a-x-** [comment]
ok, I can restore initial flagged functionality

**Comment by mastilver** [comment]
@a-x- I want to work on something more modular, it will solve your issue and few others

In the meantime, I would love to get some help on #51 as I won't be merging anything else until that's done. that way I'm sure we don't introduce new breaking changes

**Comment by Ianfeather** [comment]
@mastilver Thanks for your quick turnaround on this! It's much appreciated.

@a-x- thanks for the link to that project. That will also help us remove our webpack-runtime script too

File: lib/plugin.js [hunk 2]
```diff
@@ -42,24 +42,26 @@ ManifestPlugin.prototype.apply = function(compiler) {
...
-      var chunkName = chunk.name ? chunk.name.replace(this.opts.stripSrc, '') : null;
-
-      // Map original chunk name to output files.
-      // For nameless chunks, just map the files directly.
-      return chunk.files.reduce(function(memo, file) {
-        // Don't add hot updates to manifest
-        if (file.indexOf('hot-update') >= 0) {
+    _.merge(manifest, compilation.chunks
+      .filter(chunk => chunk.isInitial ? chunk.isInitial() : chunk.initial)
+      .reduce(function(memo, chunk) {
```
Comment (zuzusik) [inline lib/plugin.js]: It looks like if we use `(memo, chunk) => {...}` we get the right context and we can skip `.bind(this)`

File: lib/plugin.js [hunk 3]
```diff
@@ -42,24 +42,26 @@ ManifestPlugin.prototype.apply = function(compiler) {
...
+        var chunkName = chunk.name ? chunk.name.replace(this.opts.stripSrc, '') : null;
+
+        // Map original chunk name to output files.
+        // For nameless chunks, just map the files directly.
+        return chunk.files.reduce(function(memo, file) {
```
Comment (zuzusik) [inline lib/plugin.js]: same as https://github.com/danethurber/webpack-manifest-plugin/pull/48/files#r126661193, but will work only in combination with the previous (e.g. if both functions are arrow)

File: lib/plugin.js (hunk 2 above)
Comment (mastilver) [inline lib/plugin.js]: @zuzusik You are right, but it can't happens before  #53 
I did the mistake of merging this PR without caring for older node versions
I added tests to prevent this kind of mistake in the future

Comment (zuzusik) [inline lib/plugin.js]: cool, got it
